maxThreads: 20
maxJobs: 100

inputDir: '/DCEG/CGF/Bioinformatics/Production/Shalabh/variantCallingPipelineGermlineHC4/example_data/bam/'
outputDir: '/DCEG/CGF/Bioinformatics/Production/Bari/Germline_pipeline_v4_dev/test_out/'
  #'/DCEG/CGF/Bioinformatics/Production/Shalabh/variantCallingPipelineGermlineHC4/output_ScatterGather_3/'
logDir: '/DCEG/CGF/Bioinformatics/Production/Bari/Germline_pipeline_v4_dev/test_out/logs/'
tempDir: '/ttemp/bballew/'

intervalFile: '/DCEG/Projects/Exome/SequencingData/variant_scripts_V3_in_process/variant_intervals_beds/variant_calling_intervals_120430_HG19_ExomeV3_UTR_merged_padded250bp_merged_4000parts/120430_HG19_ExomeV3_UTR_merged_padded250bp_merged.intervals'
bedFile: '/DCEG/Projects/Exome/SequencingData/variant_scripts_V3_in_process/variant_intervals_beds/variant_calling_intervals_120430_HG19_ExomeV3_UTR_merged_padded250bp_merged_4000parts/120430_HG19_ExomeV3_UTR_merged_padded250bp_merged.bed'
# DV needs bed.  Can GATK use bed instead of interval, to simplify requirements?

clusterMode: 'qsub -q long.q -V -j y -o /DCEG/CGF/Bioinformatics/Production/Bari/Germline_pipeline_v4_dev/test_out/logs/'
snakePath: '/DCEG/CGF/Bioinformatics/Production/Bari/Germline_pipeline_v4_dev/variantCallingHC4/scripts/'

gatkPath: '/DCEG/Projects/Exome/SequencingData/GATK_binaries/gatk-4.0.11.0/' #gatk-package-4.0.11.0-local.jar'
# bed: '///.bed'

# hg19
refGenome: '/DCEG/CGF/Resources/Data/genome/hg19_canonical_correct_chr_order.fa'
dictionaryFile: '/DCEG/Resources/Data/genome/hg19_canonical_correct_chr_order.dict'

# gvcf: 'TRUE'  # do we want to have this option in the pipeline?
useShards: TRUE  # shards vs. chroms to parallelize
numShards: 4
modelPath: '/opt/wgs/model.ckpt' # different models for WES vs. WGS
  # note that DV is run in a singularity container, and this is the path to the models within the container.
